== ADD-ONS

=== Mifare

This section describes how the NQuire application handles mifare.

==== Context

A mifare module is an NQuire hardware option. The current module only supports reading and writing with key A.

The NQuire can be used to read and write mifare classic cards.

==== Mifare read

There are two ways to read a mifare card using the NQuire:

 - off-line: the access key and which sectors should be read are stored (configured) in the NQuire;
 - on-line: the access key and sectors to be read are transmitted to the NQuire;

===== Off-line

When a card is presented to the NQuire, the specified sectors are read using the preconfigured access key. The retrieved data is send to the connected server(s).

===== On-line

When a card is presented, only the card-num is send to the (connected) server. The server than decides what to do, eg:

 - read data from the card
 - display a message
 - activate the touchscreen

This way it is possible to:

 - support multiple keys for reading different sectors
 - interact with the user using the touchscreen in-between presenting the card and reading (or writing) the card (eg in case of writing: ask for confirmation).

NOTE: Do not use off-line mode when mifare keys are to be secret because keys, data and event messages are transmitted unencrypted using tcp and/or udp. It 'is' possible to transmit the message encoded in base64 making them unreadble for humans. However, base64 is easily recognized and decoded.

==== Mifare write

A mifare write is only implemented on-line. Off course, it is only possible to use mifare write when a mifare card is presented to the NQuire.

The server is notified of presenting a mifare card using the configured mifare read event message.

NOTE: It is possible to disable to mifare-read-success-beep so the is no 'ok' beep after the read message. That would be confusing because the transacting would not be complete after the beep: a write stilll has to be done.

===== On-line

 - The server sends a message to NQuire to write data in a certain block.
 - When the write succeeds or fails an event message is generated with the result.
 - The result is also logged in a persistent log-file (see "Transaction log-file")

==== Transaction log-file

All mifare write transactions are logged in a logfile:

log/mifare.log is accesible via ftp.

Logfiles are shifted upon the escape command: "shift mifare-log". The logfile will be named as "mifare-<shift id>.log".

The shift id is specified by the "shift mifare transaction log" escape command.

----
The server can get a "log-file too big" message indicating that the mifare transaction log is too big. This can influence performance. As a response, the server should innitiate a "shift mifare log", download the log and remove the log.
----

NOTE: When this is not done, it is possible that transactions will fail due to insufficient space to log transactions. The space to log files is also used by uploaded gif-images.

===== Log file format

Bnf format:
-----
line := <transaction-id> {<command> <result>}+
command := "W" | "I" | "D"
result := "
-----


==== Messages

===== escape commands (server to NQuire)

For a complete definition see: link:server_communication.html[server_communication.html]

[format="csv", options="header"]
|===
command,defined as
\x1b\xf8<cardnum>KaaaaaaaaaaaaR{<sector><block>}+\x03,read mifare card
\x1b\xf9<cardnum><transaction id>KaaaaaaaaaaaaW<sector><block><format><data>\x03,write data
\x1b\xf9<cardnum><transaction id>KaaaaaaaaaaaaI<sector><block>\x03,increment block
\x1b\xf9<cardnum><transaction id>KaaaaaaaaaaaaD<sector><block>\x03,decrement block
\x1b\xfahhhhhhhh\x03,shift transaction log
|===

====== Events (NQuire to server)

[format="csv", options="header"]
|===
Event,defined as
MF<cardnum>[<data>],Mifare data read. 'Data' is optional depending on the configuration. Cardnum and data formatting depends on configuration
|===

====== Configuration


|===
|conf id|value format|example|explanation

|/dev/mifare/device|'/dev/<dev>'|"/dev/ttyS2"|Don't touch this
|/dev/mifare/key_A|<nibble>12|"FFFFFFFFFFFF"|
|/dev/mifare/relevant_sectors|[<n>[,<n>]*]|"1,15"|Comma seperated list of the sectors to be read. Sector data is send in this order.

|/dev/mifare/prevent_duplicate_scan_timeout|n|3|
A detected card will be ignored when it was
the same as the last scanned mifare card within
n seconds ago.

|/dev/mifare/cardnum_format|"binary"
"hexadecimal"|"hexadecimal"|
The cardnum is formatted according this parameter:
'binary': data is send as it is (null
characters are send as null characters, etc)
'hexadecimal': all characters are transmitted in
their hexadecimal value formatted as 2 nibbles
for each character.

|/dev/mifare/msg/incomplete_scan/text|<text>|"Wait for beep\nwhen scanning"|
The error message that is displayed when a
card scan was incomplete.

|/dev/mifare/msg/access_violation/text|<text>|"Card access\ndenied"|
The message that is displayed when card
access was denied.

|===

== Touch Screen

This document describes the requirements and design for how the NQuire
application should handle the touchscreen functionality.

=== Introduction

Some customers require a possebility to interact with the NQuire. An example of
this could be an application of the NQuire in a casino for upgrading a value
card.

Choosen is to have a touchscreen for this. The NQuire should still remain a
dumb device, knowning knothing of the application it serves. This means it
will only offer the possibility to use the touchscreen. The actual application
giving the touch-screen-input meaning, is to be in the customers server.

=== Hardware

The touchscreen is a hardware option on the NQuire.

This touchscreen has a capacitive matrix of 4x4 touch-area ('keys').
The firmware is extended with an extra device: +/dev/event0+

This device spawns +struct input_event+ formatted data.

=== Requirements

R.kp.1 - The server should be able to be notified of all touch-key-press events.

R.kp.2 - It shall be possible to have a grafical touch-key visualisation.

R.kp.2.1 - A touch key can be related to an image (gif)

R.kp.2.2 - A key-press event is to be visualised.

R.kp.2.2.2 - It shall be possible to relate a different image to the released
	as to the pressed state of a touch-key.

R.kp.2.3 - It shall be possible to relate one image to more than 1 touch-key.

R.kp.2.3.1 - Images are of arbitray size (uploaded images can be smaller or bigger than 1 touch-key).

R.kp.2.3.2 - An image is visualised the moment a relation is made.

R.kp.2.3.3 - There shall be a timeout on the touchscreen visualisation, counting
	from the last key-press or layout-update.

R.kp.2.3.3.1 - The timeout shall be configurable (and can be indefinite).

R.kp.2.3.4 - All clients (udp/tcp) shall be notified of the timeout-event.

R.kp.2.3.5 - The screen shall be blanked upon a timeout.
	The normal +welcome+ text is displayed after the idle-timeout +cit.conf /cit/messages/idle/timeout+

R.kp.2.5 - The following default images shall be available:

R.kp.2.5.1 - 1 key-size button images:
	0.gif        a.gif       cross.gif
	1.gif        b.gif       mul.gif
	2.gif        c.gif	     div.gif
	3.gif        d.gif       add.gif
	4.gif        e.gif       sub.gif
	5.gif        f.gif       assign.gif
	6.gif        info.gif    down.gif
	7.gif        cancel.gif  up.gif
	8.gif        cr.gif      right.gif
	9.gif        ok.gif      left.gif
	reset.gif    ok_sign.gif

R.kp.2.6 - It shall be possible to upload alternate images.

R.kp.2.6.1 - Image names should not contain spaces or a path

R.kp.2.6.3 - The upload client is responsible for correct format of the image

R.kp.2.6.4 - Only gif images will be used by the nquire

R.kp.2.6.4.1 - It is possible to use animated gif images

R.kp.2.6.4.2 - The images should be 2 colors: white={r=255,g=255,b=255}
	and black={r=0,g=0,b=0}. Pure blue={r=0,g=0,b=255} is interpreted as
	transparent color.

R.kp.3 - It shall be possible to write text 'over' the touch-screen layout
	using escape commands.

=== Constraints

It is not possible to use an external scanner on an NQuire with a touchscreen.

This is a driver contraint: the touchscreen outputs via
stdin as well as the external scanner. Both datastreams will be mixed, which will give inconclusive results.

Therefore, external scanner input is ignored when a touchscreen is detected.

=== Design

==== Escape command interface


The following extra escape commands are to be implemented:

 * +\xf0 <image name> \x03+ : show image
 .. position image with \x2c (set pixel position)
 .. only gif images allowed
 * +\xf2 <name released> \x0d <name pressed> \x0d <pos key-id> <coupled to key-id>n \x03+ : relate image to touch-key
 .. When only 1 key is coupled, usually <pos key-id> == <coupled to key-id>
 .. the +name+ the name of the gif-image without the +.gif+ extension.
 .. it is possible to couple an image to more than 1 touch-key, simply by specifying more than 1 key-id.
 .. positions range from [0..f], starting left top:
------
           0  1  2  3
           4  5  6  7
           8  9  a  b
           c  d  e  f
------
 * +\xf3+ : show welcome text
 .. This forces the welcome tekst to be shown without delay.
 .. All touch-key to image bindings are released.
 * +\xf5+ : clear text layer only (images stay on the screen)

==== Image upload

Images can be uploaded with ftp.
For this, the folder 'img' is available when the ftp-user is logged in.
Image upload is only available when an sd-card is inserted.
The images are directly stored on the sd-card (mount --bind). As such, the size of the sd-card limits the number of images.

When no sd card is present, it is decided that it should still be possible to store a small amount of images. For this, a small seperate partition is created which is mounted instead of the sd-card to /home/ftp/img. (it is not possible to just use the remaining space of the jffs2 partition because an ftp-user could than potiontially crash the system by uploading files until no space is left on the jffs2 partition since that is the same partition as occupied by OS and application files).

Note that there can be serious performance degradation when there are a lot of images (thousends?). The ftp-user is responsible for managing those images.

==== Touch-key-press event messages

-------
packet := prefix value <CR>
prefix := "K"
value  := { {'0' .. 'f'} [<filename of image>] } | 'T'
-------

Note that:

 * the prefix is configurable in the webui.
 * the value always sends the touched key, followed by the filename of the image when an image was coupled to it. A 'T' is send on a timeout.
 * When a touch-key is pressed without having an image coupled to it (and +/dev/touch16/send_active_keys_only = true+), then only the prefix followed by the key-value is send.

=== QA

 Q1: What to do when a image is not available for positioning?
 A1: The command is simply ignored
